[package]
name = "persephone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
async-graphql = { version = "7.0.6", features = ["tracing"] }
async-graphql-axum = "7.0.6"
async-stream = "0.3.5"
async-trait = "0.1.80"
axum = { version = "0.7.5", features = ["tracing"] }
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.6.0" }
candle-nn = { git = "https://github.com/huggingface/candle.git", version = "0.6.0" }
candle-transformers = { git = "https://github.com/huggingface/candle.git", version = "0.6.0" }
clap = { version = "4.5.7", features = ["derive"] }
futures-util = "0.3.30"
hf-hub = "0.3.2"
hound = "3.5.1"
ndarray = "0.15.6"
serde = "1.0.203"
serde_json = "1.0.117"
tokenizers = "0.19.1"
tokio = { version = "1.38.0", features = ["full", "tracing"] }

[features]
metal = ["candle-core/metal", "candle-transformers/metal"]
accelerate = ["candle-core/accelerate"]
