[package]
name = "persephone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
async-graphql = { version = "7.0.3", features = ["tracing"] }
async-graphql-axum = "7.0.3"
async-stream = "0.3.5"
async-trait = "0.1.79"
axum = { version = "0.7.5", features = ["tracing"] }
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.4.2" }
candle-nn = { git = "https://github.com/huggingface/candle.git", version = "0.4.2" }
candle-transformers = { git = "https://github.com/huggingface/candle.git", version = "0.4.2" }
clap = { version = "4.5.4", features = ["derive"] }
futures-util = "0.3.30"
hf-hub = "0.3.2"
hound = "3.5.1"
ndarray = "0.15.6"
ort = { version = "2.0.0-rc.1", features = ["ndarray"] }
serde = "1.0.197"
serde_json = "1.0.115"
sqlx = { version = "0.7.4", features = ["runtime-tokio", "tls-rustls"] }
tokenizers = "0.15.2"
tokio = { version = "1.37.0", features = ["full", "tracing"] }

[features]
metal = ["candle-core/metal", "candle-transformers/metal"]
