name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: persephone-runners
    steps:
    - name: Install rustup
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        . "$HOME/.cargo/env"
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/
        key: ${{ runner.os }}-cargo-${{ hashFiles('src/assistant.rs') }}
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.7
    - name: Configure sccache
      run: |
        echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test --verbose -- --nocapture
