name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: persephone-runners
    steps:
    - name: debug
      run: |
        whoami
        ls -la ~/

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: ${{ runner.os }}-rust-${{ hashFiles('Cargo.*') }}
        restore-keys: |
          ${{ runner.os }}-rust-${{ hashFiles('Cargo.*') }}
          ${{ runner.os }}-rust-
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.7
    - name: Configure sccache
      run: |
        echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test --verbose -- --nocapture
